export const ROUTES = {
  INDEX: '/',
  HOME: '/home',
  HOW_TO_WORK: '/how-to-work',
  ACTIVATION: '/pass-activation',
  DIPLOMA: '/university',
  STUDENT: '/student',
  EMPLOYER: '/company',
  DISCOUNT: '/discount-demo',
  MANAGE: '/manage',
  GENERATE: '/generate',
  RECOVER: '/recover',
  UNIVERSITY: '/university',
  UNIVERSITY_ACCOUNT: '/uni-account',
  COMPANY: '/company',
  COMPANY_ACCOUNT: '/com-account',
  DISCOUNT_DEMO: '/discount-demo',
  PASS_ACTIVATION: '/pass-activation',
}
